swagger: "2.0"
info:
  version: 1.0.0
  title: tbrjar
  description: Draw the next book to be read
basePath: /tbrjar
tags:
  - name: Book
    description: Book endpoints
  - name: Specification
    description: The Swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  BookBody:
    type: object
    title: book
    required:
      - title
    properties:
      title:
        type: string
        example: Carrie
      author:
        type: string
        example: Stephen King
      numberOfPages:
        type: integer
        example: 340


paths:
  #BOOK
  /book:
    get:
      tags:
        - Book
      description: Fetch all books
      responses:
        200:
          description: Returns all books
    post:
      tags:
        - Book
      description: Create a new book
      parameters:
        - name: book
          in: body
          description: a book
          required: true
          schema:
            $ref: "#/definitions/BookBody"
      responses:
        200:
          description: The book was created

  /book/{id}:
    get:
      tags:
        - Book
      description: Returns the book with the specified id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the book to retrieve
          type: integer
      responses:
        200:
          description: Return the book with the specified id
        404:
          description: Book not found
    put:
      tags:
        - Book
      description: Update book with the specified id
      parameters:
      - name: id
        in: path
        required: true
        description: The id of the book to update
        type: integer
      responses:
        200:
          description: Return the updated book
        404:
          description: Book not found
    delete:
      tags:
        - Book
      description: Delete book with the specified id
      parameters:
      - name: id
        in: path
        required: true
        description: The id of the book to delete
        type: integer
      responses:
        200:
          description: The book was deleted
        404:
          description: Book not found
          
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
